#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Build application for staging or release.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Pulling down configuration settings for test environment"
        pushd "${DIR}/.."
        aws s3 cp "s3://${RF_SETTINGS_BUCKET}/.env" ".env"
        
        aws s3 cp "s3://${RF_SETTINGS_BUCKET}/.sbtopts" - >> app-backend/.sbtopts
        sort app-backend/.sbtopts | uniq > cleaned_sbtopts
        mv cleaned_sbtopts app-backend/.sbtopts
        
        popd

        echo "Building static asset bundle"
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend install
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend run build
        
        echo "Building sbt container for migrations"
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                  -f "${DIR}/../docker-compose.test.yml"\
                  build app-migrations
                  
        echo "Building batch JAR"
        docker-compose \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm --no-deps \
            build batch/assembly
            
        cp "${DIR}/../app-backend/batch/target/scala-2.11/batch-assembly.jar" \
           "${DIR}/../app-tasks/jars/batch-assembly.jar"

        echo "Building Batch container image"
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                  -f "${DIR}/../docker-compose.yml" \
                  -f "${DIR}/../docker-compose.test.yml" \
                  build batch

        echo "Building application JAR"
        docker-compose \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm --no-deps \
            build api/assembly

        echo "Building tile server JAR"
        docker-compose \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm --no-deps \
            build tile/assembly

        echo "Building backsplash JAR"
        docker-compose \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm --no-deps \
            build backsplash/assembly
            
        echo "Building container images"
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                  -f "${DIR}/../docker-compose.yml" \
                  -f "${DIR}/../docker-compose.test.yml"\
                  build nginx-api api-server nginx-tiler tile-server nginx-backsplash backsplash

        echo "Running tests"
        GIT_COMMIT="${GIT_COMMIT}" ./scripts/test
        echo "All tests pass!"
    fi
fi
