#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")

Publish container images to Elastic Container Registry (ECR) and
other artifacts to S3.
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Pulling down configuration settings for test environment"
        pushd "${DIR}/.."
        aws s3 cp "s3://rasterfoundry-testing-config-us-east-1/.env" ".env"
        popd
    
        if [[ -n "${AWS_ECR_ENDPOINT}" ]]; then
            # Build these projects as SNAPSHOT artifacts and publish to
            # Sonatype OSSRH (Snapshot Repository).
            if [ "$(whoami)" == "jenkins" ]; then
                projects=( \
                    "api" \
                    "authentication" \
                    "batch" \
                    "datamodel" \
                    "db" \
                    "tile" \
                )

                for project in "${projects[@]}"
                do
                    echo "Publishing ${project} artifact"

                    docker-compose \
                       -f "${DIR}/../docker-compose.test.yml" \
                       run --rm --no-deps \
                       -e SONATYPE_USERNAME="${SONATYPE_USERNAME}" \
                       -e SONATYPE_PASSWORD="${SONATYPE_PASSWORD}" \
                       -e PGP_HEX_KEY="${PGP_HEX_KEY}" \
                       -e PGP_PASSPHRASE="${PGP_PASSPHRASE}" \
                       build gitSnapshots "${project}/publishSigned"
                       #--entrypoint "/bin/bash" build -c "env"
                done
            fi
        else
            echo "ERROR: No AWS_ECR_ENDPOINT variable defined."
            exit 1
        fi
    fi
fi
